services:
  database:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./db_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - ${RABBITMQ_PORT}:${RABBITMQ_PORT}
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 3s
      retries: 30

  backend:
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    container_name: backend
    restart: always
    environment:
      SERVER_PORT: ${SERVER_PORT}
      VITE_BACKEND_URL: ${VITE_BACKEND_URL}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: database
      NODE_ENV: ${NODE_ENV}
      SESSION_SECRET: ${SESSION_SECRET}
      SESSION_DURATION: ${SESSION_DURATION}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      database:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  frontend:
    build:
      context: ./
      dockerfile: ./client/Dockerfile
    container_name: frontend
    restart: always
    environment:
      SERVER_PORT: ${SERVER_PORT}
      VITE_BACKEND_URL: ${VITE_BACKEND_URL}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      NODE_ENV: ${NODE_ENV}
      SESSION_SECRET: ${SESSION_SECRET}
      SESSION_DURATION: ${SESSION_DURATION}
    ports:
      - ${VITE_PORT}:${VITE_PORT}
    depends_on:
      - backend