version: '3'

services:
  database:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql

  backend:
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    container_name: backend
    restart: always
    environment:
      SERVER_PORT: ${SERVER_PORT}
      VITE_BACKEND_URL: ${VITE_BACKEND_URL}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: database
      NODE_ENV: ${NODE_ENV}
      SESSION_SECRET: ${SESSION_SECRET}
      SESSION_DURATION: ${SESSION_DURATION}
    ports:
      - "3000:3000"
    depends_on:
      - database

  frontend:
    build:
      context: ./
      dockerfile: ./client/Dockerfile
    container_name: frontend
    restart: always
    environment:
      SERVER_PORT: ${SERVER_PORT}
      VITE_BACKEND_URL: ${VITE_BACKEND_URL}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: database
      NODE_ENV: ${NODE_ENV}
      SESSION_SECRET: ${SESSION_SECRET}
      SESSION_DURATION: ${SESSION_DURATION}
    ports:
      - "5173:5173"
    depends_on:
      - backend